### PR TITLE
(#163) Fix unit tests

### LINKED ISSUE #163: Fix all unit test that are `Skipped`
# Code (files)
https://github.com/jibedoubleve/lanceur-bis/blob/48b7ce884574385ff61f634ea11609e8f9362665/src/Lanceur.Tests/ViewModels/MainViewModelShould.cs#L1

https://github.com/jibedoubleve/lanceur-bis/blob/48b7ce884574385ff61f634ea11609e8f9362665/src/Lanceur.Tests/Functional/PackagedAppManagerShould.cs#L1

# Test to fix

- [ ] `PackagedAppManagerShould.ReturnAppUniqueId`
- [ ] `PackagedAppManagerShould.CheckIsPackage`
- [ ] `MainViewModelShould.AddResultsAfterSearch`
- [ ] `MainViewModelShould.AddResultsWithParametersAfterSearch`
- [ ] `MainViewModelShould.ExecuteAnExecutableQueryResultWithParameters`
- [ ] `MainViewModelShould.ExecuteAnExecutableQueryResultWithResults`
- [ ] `MainViewModelShould.ExecuteResultWithParameter`

### PR DESCRIPTION
**Pull request by jibedoubleve**
Close #163

### CODE REVIEW

File: src/Lanceur/Views/MainViewModel.cs [hunk 1]
```diff
@@ -104,23 +105,36 @@ public class MainViewModel : ReactiveObject
...
-            var obs = this.WhenAnyObservable(vm => vm.SearchAlias, vm => vm.ExecuteAlias);
+            var obs = this
+                .WhenAnyObservable(vm => vm.SearchAlias, vm => vm.ExecuteAlias)
+                .ObserveOn(_schedulers.MainThreadScheduler);
+
             obs.Select(r => r.Results.ToObservableCollection())
+                .Log(this, "New results.", x => $"{x?.Count ?? -1} element(s)")
                 .BindTo(this, vm => vm.Results);
 
             obs.Select(r => r.KeepAlive)
```
Comment (jibedoubleve) [inline src/Lanceur/Views/MainViewModel.cs:130]: Should be removed

File: src/Lanceur/Views/MainViewModel.cs [hunk 2]
```diff
@@ -104,23 +105,36 @@ public class MainViewModel : ReactiveObject
...
                 .BindTo(this, vm => vm.KeepAlive);
 
+            this.WhenAnyObservable(vm => vm.SearchAlias, vm => vm.ExecuteAlias)
```
Comment (jibedoubleve) [inline src/Lanceur/Views/MainViewModel.cs:133]: Use `obs` instead of `this.WhenAnyObservable(vm => vm.SearchAlias, vm => vm.ExecuteAlias)`

File: src/Lanceur/Views/MainViewModel.cs [hunk 3]
```diff
@@ -192,21 +207,20 @@ private async Task<AliasResponse> OnExecuteAliasAsync(AliasExecutionRequest requ
...
             else
             {
                 var query = _cmdlineManager.BuildFromText(criterion);
-                var results = await Task.Run(() =>
-                {
-                    _log.Debug($"Search: criterion '{criterion}'");
-                    return _searchService.Search(query)
+
+                _log.Debug($"Search: criterion '{criterion}'");
+                var results = _searchService
```
Comment (jibedoubleve) [inline src/Lanceur/Views/MainViewModel.cs:218]: Should be awaited

File: src/Lanceur/Views/MainViewModel.cs [hunk 4]
```diff
@@ -192,21 +207,20 @@ private async Task<AliasResponse> OnExecuteAliasAsync(AliasExecutionRequest requ
...
+                        .Search(query)
                         .SetIconForCurrentTheme(isLight: ThemeManager.GetTheme() == ThemeManager.Themes.Light);
-                });
 
                 _log.Trace($"Search: Found {results?.Count() ?? 0} element(s)");
-                return new()
+                return new AliasResponse()
```
Comment (jibedoubleve) [inline src/Lanceur/Views/MainViewModel.cs:223]: simplify with `new()`

File: src/Lanceur.Tests/Functional/ConnectionStringShould.cs [hunk 5]
```diff
@@ -9,7 +9,7 @@ public class ConnectionStringShould
     {
         #region Methods
```
Comment (jibedoubleve) [inline src/Lanceur.Tests/Functional/ConnectionStringShould.cs:11]: Should be `[Condictional("DEBUG"]`
